"""
MVPA Decoding on GLMsingle Trial-Level Betas
=============================================
Input: GLMsingle single-trial beta 4D NIfTI + valid-trial-metadata CSV
       one volume per valid trial (shape varies per subject)

Changes from condition-level version:
  - parse_conditions replaced with load_trial_metadata()
    (reads GLMsingle metadata CSV and joins to shape onsets TSV for position/rule info)
  - LORO CV (leave-one-run-out) replaces leave-one-shape-out
    (now possible because we have trial-level betas, not condition averages)
  - vol_idx is now sequential 0..N-1 (one per valid trial)
  - All analyses filter on per-trial DataFrame joined from metadata + onsets TSV
  - Fixed typo: 'loro' -> 'logo' in decode_loro permutation call
  - Fixed: CONDITIONS_FILE singular -> per-subject CONDITIONS_FILES dict
  - Fixed: cond_df was global, now loaded per subject inside main loop
"""

import os
import warnings
import nibabel as nib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from nilearn import datasets, image
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import LeaveOneGroupOut, permutation_test_score

warnings.filterwarnings('ignore')

# ─── Paths ────────────────────────────────────────────────────────────────────

BETA_FILES = {
    'sub-001': '/usr/people/ao8210/neu502b/results/mvpa/sub001/sub-001_task-perceptXbind_single-trial-betas_4D.nii.gz',
    'sub-002': '/usr/people/ao8210/neu502b/results/mvpa/sub002/sub-002_task-perceptXbind_single-trial-betas_4D.nii.gz',
    'sub-008': '/usr/people/ao8210/neu502b/results/mvpa/sub008/sub-008_task-perceptXbind_single-trial-betas_4D.nii.gz',
}

# GLMsingle metadata: columns = events_row, trial_type, block
CONDITIONS_FILES = {
    'sub-001': '/usr/people/ao8210/neu502b/results/mvpa/sub001/sub-001_task-perceptXbind_valid-trial-metadata.csv',
    'sub-002': '/usr/people/ao8210/neu502b/results/mvpa/sub002/sub-002_task-perceptXbind_valid-trial-metadata.csv',
    'sub-008': '/usr/people/ao8210/neu502b/results/mvpa/sub008/sub-008_task-perceptXbind_valid-trial-metadata.csv',
}

# Shape onsets TSV (generated by csv_to_shape_onsets_tsv.py):
# columns = onset, duration, trial_type, run, block, trial, phase, position, rule_type
# This provides position and rule_type which are absent from GLMsingle metadata.
ONSETS_FILES = {
    'sub-001': '/usr/people/ao8210/neu502b/sub-001_combined_times_shape_onsets.tsv',
    'sub-002': '/usr/people/ao8210/neu502b/7ea7ce2b-65c3-4ff4-a9bd-ded1149f0b99_shape_onsets.tsv',
    'sub-008': '/usr/people/ao8210/neu502b/e3f4c2c2-e078-42a1-970c-cc7833d2a7b2_shape_onsets.tsv',
}

results_dir    = '/usr/people/ao8210/neu502b/results/mvpa/'
os.makedirs(results_dir, exist_ok=True)

N_PERMUTATIONS = 1000

# ─── Run mapping ──────────────────────────────────────────────────────────────

BLOCK_TO_RUN = {
    'main_run1': 1,
    'main_run2': 2,
    'main_run3': 3,
    'main_run4': 4,
}

# ─── ROI definitions (Harvard-Oxford, MNI space) ─────────────────────────────

HO_SUB_ROIS = {
    'Hippocampus': [9, 19],
}
HO_CORT_ROIS = {
    'PFC':              [1, 3, 4, 5, 6],
    'LateralOccipital': [22, 23],
    'V1_V2':            [48],
}


# ─────────────────────────────────────────────────────────────────────────────
# 1. Load and enrich trial metadata
# ─────────────────────────────────────────────────────────────────────────────

def load_trial_metadata(conditions_file, onsets_file):
    """
    Build a per-trial DataFrame suitable for MVPA analysis.

    GLMsingle metadata provides:
      events_row  : original row index in the full events TSV
      trial_type  : shape name (circle/rectangle/star/triangle)
      block       : main_run1 / main_run2 / main_run3 / main_run4

    Shape onsets TSV provides (indexed by block + trial + phase + position):
      position    : 1/2/3 (within phase)
      phase       : rule / test
      rule_type   : ABA / ABB

    We join on (block, trial_type, phase, position) extracted from the
    onsets TSV row order, which matches the GLMsingle trial order because
    both are sorted chronologically.

    Returns
    -------
    DataFrame with columns:
      vol_idx    : int  — 0-based index into beta 4D volume
      trial_type : str  — shape name
      block      : str  — run block label
      run_id     : int  — integer run number (1–4) for LORO CV
      phase      : str  — 'rule' or 'test'
      position   : int  — 1/2/3
      rule_type  : str  — ABA / ABB
      role       : str  — A / B / Aprime / Bprime (inferred from phase+position)
    """
    # Load GLMsingle metadata
    meta = pd.read_csv(conditions_file, index_col='events_row')
    meta = meta.reset_index()  # keep events_row as a column
    meta.insert(0, 'vol_idx', range(len(meta)))

    # Load shape onsets TSV — one row per stimulus event
    onsets = pd.read_csv(onsets_file, sep='\t')

    # The onsets TSV has 5 rows per trial (5 events).
    # GLMsingle metadata has one row per valid estimable event.
    # We need to match each metadata row to the correct onset row.
    #
    # Strategy: the onsets TSV is sorted by run then onset time,
    # which matches the order GLMsingle received events.
    # We index into onsets using the events_row column from metadata,
    # which is the original row index in the full onsets TSV.
    onsets = onsets.reset_index()  # add 'index' column = original row order
    onsets = onsets.rename(columns={'index': 'events_row'})

    # Merge metadata with onsets on events_row
    merged = meta.merge(
        onsets[['events_row', 'phase', 'position', 'rule_type']],
        on='events_row',
        how='left'
    )

    # Add run_id for LORO CV
    merged['run_id'] = merged['block'].map(BLOCK_TO_RUN)

    # Infer role from phase and position
    # phase=rule, position=1 -> A (first stimulus, A-slot)
    # phase=rule, position=2 -> B (second stimulus, B-slot)
    # phase=rule, position=3 -> A (ABA) or B (ABB) — the repeated stimulus
    # phase=test, position=1 -> Aprime
    # phase=test, position=2 -> Bprime
    def infer_role(row):
        if row['phase'] == 'test':
            return 'Aprime' if row['position'] == 1 else 'Bprime'
        else:  # rule phase
            if row['position'] == 1:
                return 'A'
            elif row['position'] == 2:
                return 'B'
            else:  # position 3
                return 'A' if row['rule_type'] == 'ABA' else 'B'

    merged['role'] = merged.apply(infer_role, axis=1)

    # Warn about any rows that failed to join
    missing = merged['phase'].isna().sum()
    if missing > 0:
        print(f'  Warning: {missing} trials could not be matched to onsets TSV')

    return merged


# ─────────────────────────────────────────────────────────────────────────────
# 2. Build ROI masks (Harvard-Oxford, resampled to beta space)
# ─────────────────────────────────────────────────────────────────────────────

print('\nBuilding ROI masks...')
ho_sub  = datasets.fetch_atlas_harvard_oxford('sub-maxprob-thr25-2mm')
ho_cort = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm')

# Use sub-008 as reference space for initial mask construction
ref_img = nib.load(BETA_FILES['sub-008'])

def make_mask(atlas_data, affine, label_ids, ref_img):
    mask = np.zeros(atlas_data.shape, dtype=np.int8)
    for lid in label_ids:
        mask[atlas_data == lid] = 1
    mask_img  = nib.Nifti1Image(mask, affine)
    resampled = image.resample_to_img(mask_img, ref_img, interpolation='nearest')
    return resampled.get_fdata().astype(bool)

roi_masks = {}
for name, ids in HO_SUB_ROIS.items():
    roi_masks[name] = make_mask(ho_sub.maps.get_fdata(),
                                ho_sub.maps.affine, ids, ref_img)
for name, ids in HO_CORT_ROIS.items():
    roi_masks[name] = make_mask(ho_cort.maps.get_fdata(),
                                ho_cort.maps.affine, ids, ref_img)

for name, mask in roi_masks.items():
    print(f'  {name}: {mask.sum()} voxels')


# ─────────────────────────────────────────────────────────────────────────────
# 3. Extract ROI patterns from beta file
# ─────────────────────────────────────────────────────────────────────────────

def extract_patterns(beta_4d, roi_mask, vol_indices):
    """
    Extract ROI patterns for specified volume indices.

    Parameters
    ----------
    beta_4d    : (x, y, z, n_trials) array
    roi_mask   : (x, y, z) boolean array
    vol_indices: list/array of int

    Returns
    -------
    X : (n_trials, n_voxels)
    """
    return beta_4d[roi_mask][:, vol_indices].T


# ─────────────────────────────────────────────────────────────────────────────
# 4. Decoding functions
# ─────────────────────────────────────────────────────────────────────────────

def decode_loro(X, y, groups, n_perm=N_PERMUTATIONS):
    """
    Linear SVM with Leave-One-Run-Out CV + permutation test.

    Parameters
    ----------
    X      : (n_trials, n_voxels)
    y      : (n_trials,) string labels
    groups : (n_trials,) integer run IDs for LORO splits

    Returns
    -------
    score, perm_scores, p_value, chance
    """
    unique_groups = np.unique(groups)
    if len(unique_groups) < 2:
        n_classes = len(np.unique(y))
        return np.nan, np.array([np.nan]), 1.0, 1.0 / max(n_classes, 1)

    le    = LabelEncoder()
    y_enc = le.fit_transform(y)
    clf   = make_pipeline(StandardScaler(), SVC(kernel='linear', C=1))
    logo  = LeaveOneGroupOut()

    score, perm_scores, p_value = permutation_test_score(
        clf, X, y_enc,
        cv=logo,
        groups=groups,
        n_permutations=n_perm,
        scoring='accuracy',
        random_state=42,
        n_jobs=1,
    )
    chance = 1.0 / len(le.classes_)
    return score, perm_scores, p_value, chance


def decode_cross(X_train, y_train, X_test, y_test, n_perm=N_PERMUTATIONS):
    """
    Train on one set (e.g. A-slot), test on another (e.g. B-slot).
    Permutation test shuffles test labels.

    Returns accuracy, p_value, chance.
    """
    le = LabelEncoder()
    le.fit(np.concatenate([y_train, y_test]))
    clf = make_pipeline(StandardScaler(), SVC(kernel='linear', C=1))
    clf.fit(X_train, le.transform(y_train))
    acc = (clf.predict(X_test) == le.transform(y_test)).mean()

    rng = np.random.default_rng(42)
    perm_accs = []
    for _ in range(n_perm):
        y_shuf = rng.permutation(le.transform(y_test))
        perm_accs.append((clf.predict(X_test) == y_shuf).mean())
    p_value = (np.sum(np.array(perm_accs) >= acc) + 1) / (n_perm + 1)
    chance  = 1.0 / len(le.classes_)
    return acc, p_value, chance


# ─────────────────────────────────────────────────────────────────────────────
# 5. Analysis definitions
# ─────────────────────────────────────────────────────────────────────────────
# Each analysis specifies:
#   name        : str
#   filter      : callable(trial_df) -> subset
#   label_col   : column to decode
#   group_col   : column for LORO groups ('run_id')
#   description : str
#
# CV is now LORO throughout (leave-one-run-out using run_id 1-4),
# replacing the leave-one-shape-out used for condition-level betas.
# With ~30 trials per run this gives adequate train/test splits.

ANALYSES = [
    # ── Shape identity ────────────────────────────────────────────────────────
    {
        'name':        'Shape_rule1',
        'filter':      lambda df: df[(df['phase'] == 'rule') & (df['position'] == 1)],
        'label_col':   'trial_type',
        'group_col':   'run_id',
        'description': 'Shape identity @ rule1 (A-slot)',
    },
    {
        'name':        'Shape_rule2',
        'filter':      lambda df: df[(df['phase'] == 'rule') & (df['position'] == 2)],
        'label_col':   'trial_type',
        'group_col':   'run_id',
        'description': 'Shape identity @ rule2 (B-slot)',
    },
    {
        'name':        'Shape_rule3',
        'filter':      lambda df: df[(df['phase'] == 'rule') & (df['position'] == 3)],
        'label_col':   'trial_type',
        'group_col':   'run_id',
        'description': 'Shape identity @ rule3 (A/B-slot)',
    },
    # {
    #     'name':        'Shape_test1_ABA',
    #     'filter':      lambda df: df[(df['phase'] == 'test') &
    #                                  (df['position'] == 1) &
    #                                  (df['rule_type'] == 'ABA')],
    #     'label_col':   'trial_type',
    #     'group_col':   'run_id',
    #     'description': "Shape identity @ test1/A' (ABA)",
    # },
    {
        'name':        'Shape_test1',
        'filter':      lambda df: df[(df['phase'] == 'test') &
                                     (df['position'] == 1)],
        'label_col':   'trial_type',
        'group_col':   'run_id',
        'description': "Shape identity @ test1/A'",
    },
    # {
    #     'name':        'Shape_test2_ABA',
    #     'filter':      lambda df: df[(df['phase'] == 'test') &
    #                                  (df['position'] == 2) &
    #                                  (df['rule_type'] == 'ABA')],
    #     'label_col':   'trial_type',
    #     'group_col':   'run_id',
    #     'description': "Shape identity @ test2/B' (ABA)",
    # },
    {
        'name':        'Shape_test2',
        'filter':      lambda df: df[(df['phase'] == 'test') &
                                     (df['position'] == 2)],
        'label_col':   'trial_type',
        'group_col':   'run_id',
        'description': "Shape identity @ test2/B'",
    },
    # ── Rule type ─────────────────────────────────────────────────────────────
    {
        'name':        'RuleType_test1',
        'filter':      lambda df: df[(df['phase'] == 'test') & (df['position'] == 1)],
        'label_col':   'rule_type',
        'group_col':   'run_id',
        'description': 'Rule type (ABA vs ABB) @ test1',
    },
    {
        'name':        'RuleType_test2',
        'filter':      lambda df: df[(df['phase'] == 'test') & (df['position'] == 2)],
        'label_col':   'rule_type',
        'group_col':   'run_id',
        'description': 'Rule type (ABA vs ABB) @ test2',
    },
    # ── Role ──────────────────────────────────────────────────────────────────
    {
        'name':        'Role_rule_phase',
        'filter':      lambda df: df[(df['phase'] == 'rule') &
                                     (df['position'].isin([1, 2]))],
        'label_col':   'role',
        'group_col':   'run_id',
        'description': 'Role (A vs B) during rule phase',
    },
]

CROSS_ANALYSES = [
    {
        'name':         'SlotInvariance_rule1_to_rule2',
        'train_filter': lambda df: df[(df['phase'] == 'rule') & (df['position'] == 1)],
        'test_filter':  lambda df: df[(df['phase'] == 'rule') & (df['position'] == 2)],
        'train_label':  'trial_type',
        'test_label':   'trial_type',
        'description':  'Slot invariance: train A-slot (rule1) → test B-slot (rule2)',
    },
    {
        'name':         'SlotInvariance_rule2_to_rule1',
        'train_filter': lambda df: df[(df['phase'] == 'rule') & (df['position'] == 2)],
        'test_filter':  lambda df: df[(df['phase'] == 'rule') & (df['position'] == 1)],
        'train_label':  'trial_type',
        'test_label':   'trial_type',
        'description':  'Slot invariance: train B-slot (rule2) → test A-slot (rule1)',
    },
    {
        'name':         'Generalization_rule1_to_test1_ABA',
        'train_filter': lambda df: df[(df['phase'] == 'rule') & (df['position'] == 1)],
        'test_filter':  lambda df: df[(df['phase'] == 'test') &
                                      (df['position'] == 1) &
                                      (df['rule_type'] == 'ABA')],
        'train_label':  'trial_type',
        'test_label':   'trial_type',
        'description':  "Generalization: rule1 A-slot → test1 A' (ABA)",
    },
    {
        'name':         'Generalization_rule2_to_test2_ABB',
        'train_filter': lambda df: df[(df['phase'] == 'rule') & (df['position'] == 2)],
        'test_filter':  lambda df: df[(df['phase'] == 'test') &
                                      (df['position'] == 2) &
                                      (df['rule_type'] == 'ABB')],
        'train_label':  'trial_type',
        'test_label':   'trial_type',
        'description':  "Generalization: rule2 B-slot → test2 B' (ABB)",
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# 6. Main loop over subjects and ROIs
# ─────────────────────────────────────────────────────────────────────────────

all_results       = {}
all_cross_results = {}

SUBJECTS = list(BETA_FILES.keys())

for sub in SUBJECTS:
    print(f'\n{"="*60}')
    print(f'Subject: {sub}')
    print(f'{"="*60}')

    # Load beta 4D array
    beta_img = nib.load(BETA_FILES[sub])
    beta_4d  = beta_img.get_fdata()
    print(f'  Beta shape: {beta_4d.shape}  ({beta_4d.shape[3]} valid trials)')

    # Load and enrich trial metadata for this subject
    trial_df = load_trial_metadata(CONDITIONS_FILES[sub], ONSETS_FILES[sub])
    print(f'  Trial metadata: {len(trial_df)} rows')
    print(f'    phases:     {trial_df["phase"].value_counts().to_dict()}')
    print(f'    rule_types: {trial_df["rule_type"].value_counts().to_dict()}')
    print(f'    runs:       {trial_df["run_id"].value_counts().sort_index().to_dict()}')

    # Verify vol_idx is consistent with beta file
    assert trial_df['vol_idx'].max() < beta_4d.shape[3], \
        f'vol_idx {trial_df["vol_idx"].max()} exceeds beta dim {beta_4d.shape[3]}'

    # Resample masks to this subject's beta space if needed
    sub_masks = {}
    for name, mask in roi_masks.items():
        if mask.shape == beta_4d.shape[:3]:
            sub_masks[name] = mask
        else:
            atlas_data = (ho_sub.maps.get_fdata() if name == 'Hippocampus'
                          else ho_cort.maps.get_fdata())
            atlas_affine = (ho_sub.maps.affine if name == 'Hippocampus'
                            else ho_cort.maps.affine)
            label_ids = HO_SUB_ROIS.get(name, HO_CORT_ROIS.get(name, []))
            sub_masks[name] = make_mask(atlas_data, atlas_affine,
                                        label_ids, beta_img)

    all_results[sub]       = {}
    all_cross_results[sub] = {}

    for roi_name, roi_mask in sub_masks.items():
        print(f'\n--- ROI: {roi_name} ({roi_mask.sum()} voxels) ---')
        all_results[sub][roi_name]       = {}
        all_cross_results[sub][roi_name] = {}

        # ── Standard analyses (LORO CV) ────────────────────────────────────
        for analysis in ANALYSES:
            subset = analysis['filter'](trial_df).dropna(
                subset=[analysis['label_col'], analysis['group_col']]
            )

            if len(subset) < 8:
                print(f'  Skip {analysis["name"]}: too few trials ({len(subset)})')
                continue

            vols   = subset['vol_idx'].values.astype(int)
            X      = extract_patterns(beta_4d, roi_mask, vols)
            y      = subset[analysis['label_col']].values.astype(str)
            groups = subset[analysis['group_col']].values.astype(int)

            if len(np.unique(y)) < 2:
                print(f'  Skip {analysis["name"]}: only 1 class')
                continue
            if len(np.unique(groups)) < 2:
                print(f'  Skip {analysis["name"]}: only 1 run')
                continue

            score, perm_scores, p_value, chance = decode_loro(X, y, groups)

            all_results[sub][roi_name][analysis['name']] = {
                'score':       score,
                'p_value':     p_value,
                'chance':      chance,
                'description': analysis['description'],
                'n_trials':    len(subset),
            }

            sig = ('***' if p_value < 0.001 else '**' if p_value < 0.01
                   else '*' if p_value < 0.05 else 'ns')
            print(f'  {analysis["description"]:55s}: '
                  f'acc={score:.3f}  chance={chance:.2f}  '
                  f'p={p_value:.4f} {sig}  (n={len(subset)})')

        # ── Cross-decoding analyses ────────────────────────────────────────
        for analysis in CROSS_ANALYSES:
            train_sub = analysis['train_filter'](trial_df).dropna(
                subset=[analysis['train_label']]
            )
            test_sub = analysis['test_filter'](trial_df).dropna(
                subset=[analysis['test_label']]
            )

            if len(train_sub) < 4 or len(test_sub) < 4:
                continue

            X_train = extract_patterns(beta_4d, roi_mask,
                                       train_sub['vol_idx'].values.astype(int))
            X_test  = extract_patterns(beta_4d, roi_mask,
                                       test_sub['vol_idx'].values.astype(int))
            y_train = train_sub[analysis['train_label']].values.astype(str)
            y_test  = test_sub[analysis['test_label']].values.astype(str)

            shared = np.intersect1d(y_train, y_test)
            if len(shared) < 2:
                continue
            X_train = X_train[np.isin(y_train, shared)]
            X_test  = X_test[np.isin(y_test,  shared)]
            y_train = y_train[np.isin(y_train, shared)]
            y_test  = y_test[np.isin(y_test,  shared)]

            acc, p_value, chance = decode_cross(X_train, y_train,
                                                X_test,  y_test)

            all_cross_results[sub][roi_name][analysis['name']] = {
                'score':       acc,
                'p_value':     p_value,
                'chance':      chance,
                'description': analysis['description'],
            }

            sig = ('***' if p_value < 0.001 else '**' if p_value < 0.01
                   else '*' if p_value < 0.05 else 'ns')
            print(f'  {analysis["description"]:55s}: '
                  f'acc={acc:.3f}  chance={chance:.2f}  '
                  f'p={p_value:.4f} {sig}')


# ─────────────────────────────────────────────────────────────────────────────
# 7. Save results
# ─────────────────────────────────────────────────────────────────────────────

np.save(os.path.join(results_dir, 'trial_level_results.npy'),       all_results)
np.save(os.path.join(results_dir, 'trial_level_cross_results.npy'), all_cross_results)
print(f'\nResults saved to {results_dir}')


# ─────────────────────────────────────────────────────────────────────────────
# 8. Plots
# ─────────────────────────────────────────────────────────────────────────────

def plot_subject(sub_results, sub_cross_results, sub, rois, filename):
    n_rois = len(rois)
    fig, axes = plt.subplots(2, n_rois,
                             figsize=(5 * n_rois, 10),
                             squeeze=False, facecolor='white')

    for ri, roi_name in enumerate(rois):
        # ── Standard decoding ─────────────────────────────────────────────
        ax     = axes[0][ri]
        scores, pvals, labels, chance_val = [], [], [], 0.25

        for a in ANALYSES:
            key = a['name']
            if key in sub_results.get(roi_name, {}):
                r = sub_results[roi_name][key]
                if not np.isnan(r['score']):
                    scores.append(r['score'])
                    pvals.append(r['p_value'])
                    labels.append(key.replace('Shape_', '')
                                     .replace('RuleType_', 'Rule@')
                                     .replace('Role_', 'Role@'))
                    chance_val = r['chance']

        if scores:
            colors = ['steelblue' if p < 0.05 else 'lightsteelblue'
                      for p in pvals]
            x = np.arange(len(scores))
            ax.bar(x, scores, color=colors, alpha=0.85, width=0.6)
            ax.axhline(chance_val, color='red', linestyle='--',
                       linewidth=1.2, label=f'Chance ({chance_val*100:.0f}%)')
            for xi, (sc, p) in enumerate(zip(scores, pvals)):
                star = ('***' if p < 0.001 else '**' if p < 0.01
                        else '*' if p < 0.05 else '')
                if star:
                    ax.text(xi, sc + 0.01, star, ha='center', fontsize=9)
            ax.set_xticks(x)
            ax.set_xticklabels(labels, rotation=45, ha='right', fontsize=7)
            ax.set_ylim(0, 1)
            ax.set_ylabel('Decoding accuracy')
            ax.set_title(f'{roi_name}\nStandard Decoding (LORO)', fontsize=9)
            ax.legend(fontsize=7)
        else:
            ax.set_visible(False)

        # ── Cross-decoding ────────────────────────────────────────────────
        ax     = axes[1][ri]
        scores, pvals, labels, chance_val = [], [], [], 0.25

        for a in CROSS_ANALYSES:
            key = a['name']
            if key in sub_cross_results.get(roi_name, {}):
                r = sub_cross_results[roi_name][key]
                scores.append(r['score'])
                pvals.append(r['p_value'])
                labels.append(key)
                chance_val = r['chance']

        if scores:
            colors = ['darkorange' if p < 0.05 else 'moccasin'
                      for p in pvals]
            x = np.arange(len(scores))
            ax.bar(x, scores, color=colors, alpha=0.85, width=0.5)
            # ax.axhline(chance_val, color='red', linestyle='--',
            #            linewidth=1.2, label=f'Chance ({chance_val*100:.0f}%)')
            for xi, (sc, p) in enumerate(zip(scores, pvals)):
                star = ('***' if p < 0.001 else '**' if p < 0.01
                        else '*' if p < 0.05 else '')
                if star:
                    ax.text(xi, sc + 0.01, star, ha='center', fontsize=9)
            ax.set_xticks(x)
            ax.set_xticklabels(labels, rotation=45, ha='right', fontsize=7)
            ax.set_ylim(0, 1)
            ax.set_ylabel('Cross-decoding accuracy')
            ax.set_title(f'{roi_name}\nCross-Decoding', fontsize=9)
            ax.legend(fontsize=7)
        else:
            ax.set_visible(False)

    plt.suptitle(f'MVPA Results — {sub} (GLMsingle trial-level betas)',
                 fontsize=13, y=1.01)
    plt.tight_layout()
    out = os.path.join(results_dir, filename)
    plt.savefig(out, dpi=150, bbox_inches='tight')
    plt.show()
    print(f'Saved → {out}')


rois = list(roi_masks.keys())
for sub in SUBJECTS:
    plot_subject(
        all_results[sub],
        all_cross_results[sub],
        sub, rois,
        f'{sub}_trial_level_mvpa.png'
    )

print('\nDone.')